/**
 * Regenerates tests/vectors.txt, the cross-platform test vectors.
 *
 * Legacy expectations come from the vendored original implementation in tests/original/, so they
 * are the real thing rather than values copied by hand. Modern (PBKDF2) expectations have no
 * upstream to compare against - that mode is new to this project - so they are pinned from the
 * extension's implementation and exist to keep the three platforms in lockstep with each other.
 *
 * Run with:  node tests/generate_vectors.mjs
 */
import { writeFile } from "node:fs/promises";
import { MASTER_PASSWORDS, originalLegacyPassword } from "./original.mjs";
import { extensionLegacyPassword, extensionModernPassword } from "./extension_internals.mjs";

const DOMAINS = ["example.com", "bbc.com", "cam.ac.uk", "mintmobile.com"];

const HEADER = `\
# Cross-platform PwdHash test vectors. Generated by tests/generate_vectors.mjs - do not edit.
#
# One vector per line, fields separated by a single space:
#
#     <kind> <base64 master password> <base64 domain> <base64 expected password>
#
# The fields are base64-encoded UTF-8 because some expected legacy passwords contain NUL bytes:
# the original exhausts its pool of "extra" characters once the master password reaches 24
# characters and pads with charCode 0 from there on. Every platform must reproduce that.
#
# kinds:
#   legacy  HMAC-MD5, must match the original PwdHash exactly (tests/original/)
#   modern  PBKDF2-SHA256, must match across this project's extension, website and Android app
`;

const b64 = (value) => Buffer.from(value, "utf8").toString("base64");
const line = (kind, master, domain, expected) =>
    `${kind} ${b64(master)} ${b64(domain)} ${b64(expected)}`;

const lines = [];
for (const domain of DOMAINS) {
    for (const master of MASTER_PASSWORDS) {
        lines.push(line("legacy", master, domain, originalLegacyPassword(master, domain)));
    }
}
for (const domain of DOMAINS) {
    for (const master of MASTER_PASSWORDS) {
        // The Android PBKDF2 provider is fed a char[], so leave non-ASCII master passwords out of
        // the modern vectors until that encoding has been checked on a device.
        if (/[^\x20-\x7e]/.test(master)) continue;
        lines.push(line("modern", master, domain, await extensionModernPassword(master, domain)));
    }
}

// Belt and braces: the extension's legacy output is what actually ships, so prove it agrees with
// the original before writing the original's answers out as everyone's expectations.
for (const domain of DOMAINS) {
    for (const master of MASTER_PASSWORDS) {
        if (extensionLegacyPassword(master, domain) !== originalLegacyPassword(master, domain)) {
            throw new Error(`extension disagrees with the original: ${master} @ ${domain}`);
        }
    }
}

const content = `${HEADER}\n${lines.join("\n")}\n`;
await writeFile(new URL("vectors.txt", import.meta.url), content);
console.log(`Wrote ${lines.length} vectors`);
