/**
 * Regenerates tests/vectors.txt, the cross-platform test vectors.
 *
 * Legacy expectations come from the vendored original implementation in tests/original/, so they
 * are the real thing rather than values copied by hand. Modern (PBKDF2) expectations have no
 * upstream to compare against - that mode is new to this project - so they are pinned from the
 * extension's implementation and exist to keep the three platforms in lockstep with each other.
 *
 * Run with:  node tests/generate_vectors.mjs
 */
import { readFile, writeFile } from "node:fs/promises";
import { MASTER_PASSWORDS, originalDomain, originalLegacyPassword } from "./original.mjs";
import { extensionLegacyPassword, extensionModernPassword } from "./extension_internals.mjs";

const domains = await import("../Chrome/src/js/domain-extractor.js").then((m) => m.default);
domains.setPublicSuffixRules(
    await readFile(new URL("../Chrome/src/data/public-suffix-list.txt", import.meta.url), "utf8")
);

const DOMAINS = ["example.com", "bbc.com", "cam.ac.uk", "mintmobile.com"];

const HEADER = `\
# Cross-platform PwdHash test vectors. Generated by tests/generate_vectors.mjs - do not edit.
#
# One vector per line, fields separated by a single space:
#
#     <kind> <base64 master password> <base64 domain> <base64 expected password>
#
# The fields are base64-encoded UTF-8 because some expected legacy passwords contain NUL bytes:
# the original exhausts its pool of "extra" characters once the master password reaches 24
# characters and pads with charCode 0 from there on. Every platform must reproduce that.
#
# kinds:
#   legacy  HMAC-MD5, must match the original PwdHash exactly (tests/original/)
#   modern  PBKDF2-SHA256, must match across this project's extension, website and Android app
`;

const b64 = (value) => Buffer.from(value, "utf8").toString("base64");
const line = (kind, master, domain, expected) =>
    `${kind} ${b64(master)} ${b64(domain)} ${b64(expected)}`;

const lines = [];
for (const domain of DOMAINS) {
    for (const master of MASTER_PASSWORDS) {
        lines.push(line("legacy", master, domain, originalLegacyPassword(master, domain)));
    }
}
for (const domain of DOMAINS) {
    for (const master of MASTER_PASSWORDS) {
        // The Android PBKDF2 provider is fed a char[], so leave non-ASCII master passwords out of
        // the modern vectors until that encoding has been checked on a device.
        if (/[^\x20-\x7e]/.test(master)) continue;
        lines.push(line("modern", master, domain, await extensionModernPassword(master, domain)));
    }
}

// Belt and braces: the extension's legacy output is what actually ships, so prove it agrees with
// the original before writing the original's answers out as everyone's expectations.
for (const domain of DOMAINS) {
    for (const master of MASTER_PASSWORDS) {
        if (extensionLegacyPassword(master, domain) !== originalLegacyPassword(master, domain)) {
            throw new Error(`extension disagrees with the original: ${master} @ ${domain}`);
        }
    }
}

const content = `${HEADER}\n${lines.join("\n")}\n`;
await writeFile(new URL("vectors.txt", import.meta.url), content);

// ---- domain vectors ----

const DOMAIN_INPUTS = [
    "example.com",
    "www.bbc.com",
    "edition.cnn.com",
    "accounts.x.com",
    "secure.ing.nl",
    "mail.google.com",
    "www.bbc.co.uk",
    "login.example.co.uk",
    "login.cam.ac.uk",
    "www.imperial.ac.uk",
    "www.example.me.uk",
    "www.example.ltd.uk",
    "www.gov.uk",
    "www.mysite.uk.com",
    "login.example.ne.jp",
    "shop.example.com.au",
    "a.b.example.io",
    "my.mintmobile.com",
    "myapp.herokuapp.com",
    "other.herokuapp.com",
    "user.github.io",
    "city.kobe.jp",
    "foo.city.kobe.jp",
    "bar.foo.ck",
    "www.ck",
    "localhost",
    "192.168.0.1",
    "https://www.bbc.com/news",
    "https://login.example.co.uk/account?next=/home",
    "http://example.com",
    "https://WWW.Example.CO.UK/login",
    "example.com:8443",
    "https://user:secret@www.example.com/x",
    "xn--mnchen-3ya.de",
    "www.xn--mnchen-3ya.de"
];

const domainLines = DOMAIN_INPUTS.map((input) =>
    [
        b64(input),
        b64(originalDomain(input)),
        b64(domains.extractModernDomain(domains.hostFromInput(input)))
    ].join(" ")
);

// The shipped legacy extractor has to agree with the original for every one of these.
for (const input of DOMAIN_INPUTS) {
    if (domains.extractLegacyDomain(input) !== originalDomain(input)) {
        throw new Error(`legacy extractor disagrees with the original for ${input}`);
    }
}

const DOMAIN_HEADER = `\
# Domain extraction vectors. Generated by tests/generate_vectors.mjs - do not edit.
#
#     <base64 input> <base64 legacy domain> <base64 modern domain>
#
# Legacy answers come from the vendored original implementation (tests/original/) and are frozen:
# changing one means passwords made with the original PwdHash stop working. Modern answers come
# from the pinned Public Suffix List snapshot in */data/public-suffix-list.txt.
#
# The two differ on purpose. Legacy never lowercases and keeps a port in the salt, because the
# original did; modern parses the input as a URL first.
`;

await writeFile(
    new URL("domain-vectors.txt", import.meta.url),
    `${DOMAIN_HEADER}\n${domainLines.join("\n")}\n`
);

console.log(`Wrote ${lines.length} password vectors and ${domainLines.length} domain vectors`);
